apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: weather-app-namespace
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8070
  selector:
    app: weather-app
